add redux; filtered movies by genres
htmlacademy-react/469679-what-to-watch-5 pull request #7
Opened 2020-10-17 19:46 UTC by viktoriianosik

2020-10-18 18:09 UTC, ruslanmalogulko requested changes

2020-10-18 18:09 UTC, ruslanmalogulko commented on src/components/genres-list/genres-list.jsx
> +  movies: PropTypes.arrayOf(MovieProp),
```suggestion
  movies: PropTypes.arrayOf(MovieProp).isRequired,
```
поскольку проверок в коде на то что movies могут быть не переданы нет и если разработчик забудет передать в компонент movies, приложение упадет еще на попытке сделать `movies.map` или `movies.forEach`

2020-10-18 18:09 UTC, ruslanmalogulko commented on src/components/main/main.jsx
> +export {Main};
а где это используется?

2020-10-18 18:09 UTC, ruslanmalogulko commented on src/filter.js
> +    return movies.slice().filter((movie) => movie.genre === genre);
```suggestion
    return movies.filter((movie) => movie.genre === genre);
```
`.slice` вроде бы как и не нужет, `movies` уже массив

2020-10-18 18:09 UTC, ruslanmalogulko commented on src/store/action.js
> +
```suggestion
```

2020-10-18 18:09 UTC, ruslanmalogulko commented on src/store/reducer.js
> +export {reducer};
```suggestion
export const reducer = (state = initialState, action) => {
  switch (action.type) {
    case ActionType.CHANGE_GENRE:
      return extend(state, {
        genre: action.payload,
      });
    case ActionType.FILTER_MOVIES_LIST:
      return extend(state, {
        filteredMovies: action.payload,
      });
  }

  return state;
};
```

2020-10-19 19:36 UTC, viktoriianosik commented on src/components/main/main.jsx
> +export {Main};
по примеру учебного проекта - оставила для тестов на потом.

2020-10-20 15:36 UTC, ruslanmalogulko approved these changes

2020-10-20 15:37 UTC, merged